#!/bin/bash

# find your last watched (accessed) video in a folder

MAX_TIME=0

for file in *.mkv
do
    UNIX_TIME=$(stat -c%X "${file}")
    if [[ $UNIX_TIME -gt $MAX_TIME ]]; then
        MAX_TIME=$UNIX_TIME
        FILE_NAME="$file"
        HUMAN_TIME=$(stat -c%x "${file}")
    fi
done

echo $FILE_NAME
echo $HUMAN_TIME